/* tslint:disable */
/* eslint-disable */
/**
 * Demo API
 * Demo API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * UserForm model
 * @export
 * @interface UserForm
 */
export interface UserForm {
    /**
     * 
     * @type {string}
     * @memberof UserForm
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserForm
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof UserForm
     */
    firstName: string;
}

export function UserFormFromJSON(json: any): UserForm {
    return UserFormFromJSONTyped(json, false);
}

export function UserFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'lastName': json['lastName'],
        'firstName': json['firstName'],
    };
}

export function UserFormToJSON(value?: UserForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'lastName': value.lastName,
        'firstName': value.firstName,
    };
}


